from translations import COUNTRY_NAMES_EN, COUNTRY_NAMES_RU

COUNTRIES: list[str] = [
    "Afgʻoniston", "Albaniya", "Jazoir", "Andorra", "Angola", "Antigua va Barbuda",
    "Argentina", "Armaniston", "Avstraliya", "Avstriya", "Ozarbayjon", "Bagama orollari",
    "Bahrayn", "Bangladesh", "Barbados", "Belarus", "Belgiya", "Beliz", "Benin",
    "Butan", "Boliviya", "Bosniya va Gertsegovina", "Botsvana", "Braziliya", "Bruney",
    "Bolgariya", "Burkina Faso", "Burundi", "Kabo Verde", "Kambodja", "Kamerun",
    "Kanada", "Markaziy Afrika Respublikasi", "Chad", "Chili", "Xitoy", "Kolumbiya",
    "Komor orollari", "Kongo Demokratik Respublikasi", "Kongo Respublikasi",
    "Kosta Rika", "Xorvatiya", "Kuba", "Qibris", "Chexiya", "Daniya", "Jibuti",
    "Dominika", "Dominikan Respublikasi", "Ekvador", "Misr", "Salvador",
    "Ekvatorial Gvineya", "Eritreya", "Estoniya", "Esvatini", "Efiopiya", "Fiji",
    "Finlandiya", "Fransiya", "Gabon", "Gambiya", "Gruziya", "Germaniya", "Gana",
    "Gretsiya", "Grenada", "Gvatemala", "Gvineya", "Gvineya-Bisau", "Gayana",
    "Gaiti", "Gonduras", "Vengriya", "Islandiya", "Hindiston", "Indoneziya", "Eron",
    "Iroq", "Irlandiya", "Isroil", "Italiya", "Yamayka", "Yaponiya", "Iordaniya",
    "Qozogʻiston", "Keniya", "Kiribati", "Kuvayt", "Qirgʻiziston", "Laos", "Latviya",
    "Livan", "Lesoto", "Liberiya", "Liviya", "Lixtenshteyn", "Litva", "Lyuksemburg",
    "Madagaskar", "Malavi", "Malayziya", "Maldiv orollari", "Mali", "Malta",
    "Marshall orollari", "Mavritaniya", "Mavrikiy", "Meksika", "Mikroneziya",
    "Moldova", "Monako", "Moʻgʻuliston", "Chernogoriya", "Marokash", "Mozambik",
    "Myanma", "Namibiya", "Nauru", "Nepal", "Niderlandiya", "Yangi Zelandiya",
    "Nikaragua", "Niger", "Nigeriya", "Shimoliy Koreya", "Shimoliy Makedoniya",
    "Norvegiya", "Ummon", "Pokiston", "Palau", "Falastin", "Panama",
    "Papua Yangi Gvineya", "Paragvay", "Peru", "Filippin", "Polsha", "Portugaliya",
    "Qatar", "Ruminiya", "Rossiya", "Ruanda", "Sent Kitts va Nevis", "Sent Lusiya",
    "Sent Vinsent va Grenadinlar", "Samoa", "San Marino", "San-Tome va Prinsipi",
    "Saudiya Arabistoni", "Senegal", "Serbiya", "Seyshell orollari", "Syerra Leone",
    "Singapur", "Slovakiya", "Sloveniya", "Solomon orollari", "Somali", "Janubiy Afrika",
    "Janubiy Koreya", "Janubiy Sudan", "Ispaniya", "Shri Lanka", "Sudan", "Surinam",
    "Shvetsiya", "Shveytsariya", "Suriya", "Tayvan", "Tojikiston", "Tanzaniya",
    "Tailand", "Sharqiy Timor", "Togo", "Tonga", "Trinidad va Tobago", "Tunis",
    "Turkiya", "Turkmaniston", "Tuvalu", "Uganda", "Ukraina", "Birlashgan Arab Amirliklari",
    "Buyuk Britaniya", "Amerika Qoʻshma Shtatlari", "Urugvay", "Oʻzbekiston",
    "Vanuatu", "Vatikan", "Venesuela", "Vyetnam", "Yaman", "Zambiya", "Zimbabve",
]

COUNTRIES_SET: set[str] = set(COUNTRIES)

# Maps English name (sent by map.html) → Uzbek internal name
MAP_EN_TO_UZ: dict[str, str] = {
    "Afghanistan": "Afgʻoniston", "Albania": "Albaniya", "Algeria": "Jazoir",
    "Andorra": "Andorra", "Angola": "Angola", "Antigua and Barbuda": "Antigua va Barbuda",
    "Argentina": "Argentina", "Armenia": "Armaniston", "Australia": "Avstraliya",
    "Austria": "Avstriya", "Azerbaijan": "Ozarbayjon", "Bahamas": "Bagama orollari",
    "Bahrain": "Bahrayn", "Bangladesh": "Bangladesh", "Barbados": "Barbados",
    "Belarus": "Belarus", "Belgium": "Belgiya", "Belize": "Beliz", "Benin": "Benin",
    "Bhutan": "Butan", "Bolivia": "Boliviya", "Bosnia and Herzegovina": "Bosniya va Gertsegovina",
    "Botswana": "Botsvana", "Brazil": "Braziliya", "Brunei": "Bruney",
    "Bulgaria": "Bolgariya", "Burkina Faso": "Burkina Faso", "Burundi": "Burundi",
    "Cape Verde": "Kabo Verde", "Cambodia": "Kambodja", "Cameroon": "Kamerun",
    "Canada": "Kanada", "Central African Republic": "Markaziy Afrika Respublikasi",
    "Chad": "Chad", "Chile": "Chili", "China": "Xitoy", "Colombia": "Kolumbiya",
    "Comoros": "Komor orollari",
    "Democratic Republic of the Congo": "Kongo Demokratik Respublikasi",
    "Republic of the Congo": "Kongo Respublikasi",
    "Costa Rica": "Kosta Rika", "Croatia": "Xorvatiya", "Cuba": "Kuba",
    "Cyprus": "Qibris", "Czech Republic": "Chexiya", "Denmark": "Daniya",
    "Djibouti": "Jibuti", "Dominica": "Dominika", "Dominican Republic": "Dominikan Respublikasi",
    "Ecuador": "Ekvador", "Egypt": "Misr", "El Salvador": "Salvador",
    "Equatorial Guinea": "Ekvatorial Gvineya", "Eritrea": "Eritreya",
    "Estonia": "Estoniya", "Eswatini": "Esvatini", "Ethiopia": "Efiopiya",
    "Fiji": "Fiji", "Finland": "Finlandiya", "France": "Fransiya", "Gabon": "Gabon",
    "Gambia": "Gambiya", "Georgia": "Gruziya", "Germany": "Germaniya", "Ghana": "Gana",
    "Greece": "Gretsiya", "Grenada": "Grenada", "Guatemala": "Gvatemala",
    "Guinea": "Gvineya", "Guinea-Bissau": "Gvineya-Bisau", "Guyana": "Gayana",
    "Haiti": "Gaiti", "Honduras": "Gonduras", "Hungary": "Vengriya",
    "Iceland": "Islandiya", "India": "Hindiston", "Indonesia": "Indoneziya",
    "Iran": "Eron", "Iraq": "Iroq", "Ireland": "Irlandiya", "Israel": "Isroil",
    "Italy": "Italiya", "Jamaica": "Yamayka", "Japan": "Yaponiya",
    "Jordan": "Iordaniya", "Kazakhstan": "Qozogʻiston", "Kenya": "Keniya",
    "Kiribati": "Kiribati", "Kuwait": "Kuvayt", "Kyrgyzstan": "Qirgʻiziston",
    "Laos": "Laos", "Latvia": "Latviya", "Lebanon": "Livan", "Lesotho": "Lesoto",
    "Liberia": "Liberiya", "Libya": "Liviya", "Liechtenstein": "Lixtenshteyn",
    "Lithuania": "Litva", "Luxembourg": "Lyuksemburg", "Madagascar": "Madagaskar",
    "Malawi": "Malavi", "Malaysia": "Malayziya", "Maldives": "Maldiv orollari",
    "Mali": "Mali", "Malta": "Malta", "Marshall Islands": "Marshall orollari",
    "Mauritania": "Mavritaniya", "Mauritius": "Mavrikiy", "Mexico": "Meksika",
    "Micronesia": "Mikroneziya", "Moldova": "Moldova", "Monaco": "Monako",
    "Mongolia": "Moʻgʻuliston", "Montenegro": "Chernogoriya", "Morocco": "Marokash",
    "Mozambique": "Mozambik", "Myanmar": "Myanma", "Namibia": "Namibiya",
    "Nauru": "Nauru", "Nepal": "Nepal", "Netherlands": "Niderlandiya",
    "New Zealand": "Yangi Zelandiya", "Nicaragua": "Nikaragua", "Niger": "Niger",
    "Nigeria": "Nigeriya", "North Korea": "Shimoliy Koreya",
    "North Macedonia": "Shimoliy Makedoniya", "Norway": "Norvegiya", "Oman": "Ummon",
    "Pakistan": "Pokiston", "Palau": "Palau", "Palestine": "Falastin",
    "Panama": "Panama", "Papua New Guinea": "Papua Yangi Gvineya",
    "Paraguay": "Paragvay", "Peru": "Peru", "Philippines": "Filippin",
    "Poland": "Polsha", "Portugal": "Portugaliya", "Qatar": "Qatar",
    "Romania": "Ruminiya", "Russia": "Rossiya", "Rwanda": "Ruanda",
    "Saint Kitts and Nevis": "Sent Kitts va Nevis", "Saint Lucia": "Sent Lusiya",
    "Saint Vincent and the Grenadines": "Sent Vinsent va Grenadinlar",
    "Samoa": "Samoa", "San Marino": "San Marino",
    "Sao Tome and Principe": "San-Tome va Prinsipi", "Saudi Arabia": "Saudiya Arabistoni",
    "Senegal": "Senegal", "Serbia": "Serbiya", "Seychelles": "Seyshell orollari",
    "Sierra Leone": "Syerra Leone", "Singapore": "Singapur", "Slovakia": "Slovakiya",
    "Slovenia": "Sloveniya", "Solomon Islands": "Solomon orollari", "Somalia": "Somali",
    "South Africa": "Janubiy Afrika", "South Korea": "Janubiy Koreya",
    "South Sudan": "Janubiy Sudan", "Spain": "Ispaniya", "Sri Lanka": "Shri Lanka",
    "Sudan": "Sudan", "Suriname": "Surinam", "Sweden": "Shvetsiya",
    "Switzerland": "Shveytsariya", "Syria": "Suriya", "Taiwan": "Tayvan",
    "Tajikistan": "Tojikiston", "Tanzania": "Tanzaniya", "Thailand": "Tailand",
    "Timor-Leste": "Sharqiy Timor", "Togo": "Togo", "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad va Tobago", "Tunisia": "Tunis",
    "Turkey": "Turkiya", "Turkmenistan": "Turkmaniston", "Tuvalu": "Tuvalu",
    "Uganda": "Uganda", "Ukraine": "Ukraina",
    "United Arab Emirates": "Birlashgan Arab Amirliklari",
    "United Kingdom": "Buyuk Britaniya", "United States": "Amerika Qoʻshma Shtatlari",
    "Uruguay": "Urugvay", "Uzbekistan": "Oʻzbekiston", "Vanuatu": "Vanuatu",
    "Vatican City": "Vatikan", "Venezuela": "Venesuela", "Vietnam": "Vyetnam",
    "Yemen": "Yaman", "Zambia": "Zambiya", "Zimbabwe": "Zimbabve",
}

# Lookup: any-language lowercase → UZ internal name
MAP_ANY_TO_UZ: dict[str, str] = {}
for _uz in COUNTRIES:
    MAP_ANY_TO_UZ[_uz.lower()] = _uz
for _en, _uz in MAP_EN_TO_UZ.items():
    MAP_ANY_TO_UZ[_en.lower()] = _uz
for _uz, _en in COUNTRY_NAMES_EN.items():
    MAP_ANY_TO_UZ[_en.lower()] = _uz
for _uz, _ru in COUNTRY_NAMES_RU.items():
    MAP_ANY_TO_UZ[_ru.lower()] = _uz

COUNTRIES_CAPITALS: dict[str, str] = {
    "Afgʻoniston": "Kobul", "Albaniya": "Tirana", "Jazoir": "Jazoir",
    "Andorra": "Andorra la Vella", "Angola": "Luanda", "Antigua va Barbuda": "Sent-Jons",
    "Argentina": "Buenos-Ayres", "Armaniston": "Yerevan", "Avstraliya": "Kanberra",
    "Avstriya": "Vena", "Ozarbayjon": "Boku", "Bagama orollari": "Nassau",
    "Bahrayn": "Manama", "Bangladesh": "Dakka", "Barbados": "Bridjtaun",
    "Belarus": "Minsk", "Belgiya": "Bryussel", "Beliz": "Belmopan",
    "Benin": "Porto-Novo", "Butan": "Thimphu", "Boliviya": "Sukre",
    "Bosniya va Gertsegovina": "Sarayevo", "Botsvana": "Gaborone", "Braziliya": "Brazilia",
    "Bruney": "Bandar Seri Begavon", "Bolgariya": "Sofiya", "Burkina Faso": "Uagadugu",
    "Burundi": "Gitega", "Kabo Verde": "Praya", "Kambodja": "Pnompen",
    "Kamerun": "Yaunde", "Kanada": "Ottava", "Markaziy Afrika Respublikasi": "Bangui",
    "Chad": "Njamena", "Chili": "Santyago", "Xitoy": "Pekin",
    "Kolumbiya": "Bogota", "Komor orollari": "Moroni",
    "Kongo Demokratik Respublikasi": "Kinshasa", "Kongo Respublikasi": "Brazzavil",
    "Kosta Rika": "San-Xose", "Xorvatiya": "Zagreb", "Kuba": "Gavana",
    "Qibris": "Nikosiya", "Chexiya": "Praga", "Daniya": "Kopengagen",
    "Jibuti": "Jibuti", "Dominika": "Rozo", "Dominikan Respublikasi": "Santo-Domingo",
    "Ekvador": "Kito", "Misr": "Qohira", "Salvador": "San-Salvador",
    "Ekvatorial Gvineya": "Malabo", "Eritreya": "Asmara", "Estoniya": "Tallin",
    "Esvatini": "Mbabane", "Efiopiya": "Addis-Abeba", "Fiji": "Suva",
    "Finlandiya": "Xelsinki", "Fransiya": "Parij", "Gabon": "Librevil",
    "Gambiya": "Banjul", "Gruziya": "Tbilisi", "Germaniya": "Berlin",
    "Gana": "Akkra", "Gretsiya": "Afina", "Grenada": "Sent-Jorj",
    "Gvatemala": "Gvatemala Siti", "Gvineya": "Konakri", "Gvineya-Bisau": "Bisau",
    "Gayana": "Jorjtaun", "Gaiti": "Port-o-Prens", "Gonduras": "Tegusigalpa",
    "Vengriya": "Budapesht", "Islandiya": "Reykyavik", "Hindiston": "Yangi Dehli",
    "Indoneziya": "Jakarta", "Eron": "Tehron", "Iroq": "Bagʻdod",
    "Irlandiya": "Dublin", "Isroil": "Tel Aviv", "Italiya": "Rim",
    "Yamayka": "Kingston", "Yaponiya": "Tokio", "Iordaniya": "Ammon",
    "Qozogʻiston": "Astana", "Keniya": "Nayrobi", "Kiribati": "Tarava",
    "Kuvayt": "Kuvayt Siti", "Qirgʻiziston": "Bishkek", "Laos": "Vientian",
    "Latviya": "Riga", "Livan": "Bayrut", "Lesoto": "Maseru",
    "Liberiya": "Monroviya", "Liviya": "Tripoli", "Lixtenshteyn": "Vaduz",
    "Litva": "Vilnyus", "Lyuksemburg": "Lyuksemburg", "Madagaskar": "Antananarivo",
    "Malavi": "Lilongve", "Malayziya": "Kuala-Lumpur", "Maldiv orollari": "Male",
    "Mali": "Bamako", "Malta": "Valletta", "Marshall orollari": "Majuro",
    "Mavritaniya": "Nuakshot", "Mavrikiy": "Port-Lui", "Meksika": "Mexiko Siti",
    "Mikroneziya": "Palikir", "Moldova": "Kishinyov", "Monako": "Monako",
    "Moʻgʻuliston": "Ulan-Bator", "Chernogoriya": "Podgoritsa", "Marokash": "Rabat",
    "Mozambik": "Maputo", "Myanma": "Naypyido", "Namibiya": "Vindhuk",
    "Nauru": "Yaren", "Nepal": "Katmandu", "Niderlandiya": "Amsterdam",
    "Yangi Zelandiya": "Vellington", "Nikaragua": "Managua", "Niger": "Niamey",
    "Nigeriya": "Abuja", "Shimoliy Koreya": "Pxenyan", "Shimoliy Makedoniya": "Skopye",
    "Norvegiya": "Oslo", "Ummon": "Maskat", "Pokiston": "Islomobod",
    "Palau": "Ngerulmud", "Falastin": "Sharqiy Quddus", "Panama": "Panama Siti",
    "Papua Yangi Gvineya": "Port-Moresbi", "Paragvay": "Asunsion", "Peru": "Lima",
    "Filippin": "Manila", "Polsha": "Varshava", "Portugaliya": "Lissabon",
    "Qatar": "Doha", "Ruminiya": "Buxarest", "Rossiya": "Moskva",
    "Ruanda": "Kigali", "Sent Kitts va Nevis": "Baster", "Sent Lusiya": "Kastri",
    "Sent Vinsent va Grenadinlar": "Kingstaun", "Samoa": "Apia",
    "San Marino": "San Marino", "San-Tome va Prinsipi": "San-Tome",
    "Saudiya Arabistoni": "Riyod", "Senegal": "Dakar", "Serbiya": "Belgrad",
    "Seyshell orollari": "Viktoriya", "Syerra Leone": "Fritaun", "Singapur": "Singapur",
    "Slovakiya": "Bratislava", "Sloveniya": "Lyublyana", "Solomon orollari": "Honiara",
    "Somali": "Mogadishu", "Janubiy Afrika": "Pretoriya", "Janubiy Koreya": "Seul",
    "Janubiy Sudan": "Juba", "Ispaniya": "Madrid",
    "Shri Lanka": "Shri Jayavardenepura Kotte", "Sudan": "Xartum",
    "Surinam": "Paramaribo", "Shvetsiya": "Stokgolm", "Shveytsariya": "Bern",
    "Suriya": "Damashq", "Tayvan": "Taypey", "Tojikiston": "Dushanbe",
    "Tanzaniya": "Dodoma", "Tailand": "Bangkok", "Sharqiy Timor": "Dili",
    "Togo": "Lome", "Tonga": "Nukualofa", "Trinidad va Tobago": "Port-of-Speyn",
    "Tunis": "Tunis", "Turkiya": "Anqara", "Turkmaniston": "Ashxobod",
    "Tuvalu": "Funafuti", "Uganda": "Kampala", "Ukraina": "Kiyev",
    "Birlashgan Arab Amirliklari": "Abu-Dabi", "Buyuk Britaniya": "London",
    "Amerika Qoʻshma Shtatlari": "Vashington, D.C.", "Urugvay": "Montevideo",
    "Oʻzbekiston": "Toshkent", "Vanuatu": "Port-Vila", "Vatikan": "Vatikan Siti",
    "Venesuela": "Karakas", "Vyetnam": "Xanoy", "Yaman": "Sano",
    "Zambiya": "Lusaka", "Zimbabve": "Harare",
}

COUNTRY_HINTS_UZ: dict[str, str] = {
    "Afgʻoniston": "Bu davlat Osiyoda joylashgan, poytaxti Kobul.",
    "Albaniya": "Yevropaning janubi-sharqida, Adriatik dengizi sohilida, poytaxti Tirana.",
    "Jazoir": "Afrikada eng katta maydonga ega, poytaxti Jazoir.",
    "Andorra": "Pireney togʻlarida kichik knyazlik, poytaxti Andorra la Vella.",
    "Angola": "Janubiy Afrikada, neft va olmos resurslari, poytaxti Luanda.",
    "Antigua va Barbuda": "Karib dengizidagi orollar, poytaxti Sent-Jons.",
    "Argentina": "Janubiy Amerikada, tango va futbol, poytaxti Buenos-Ayres.",
    "Armaniston": "Kavkazda, qadimiy monastirlar, poytaxti Yerevan.",
    "Avstraliya": "Okeaniyada, kenguru va koala, poytaxti Kanberra.",
    "Avstriya": "Yevropada, Alplar va klassik musiqa, poytaxti Vena.",
    "Ozarbayjon": "Kavkazda, Xazar dengizi, poytaxti Boku.",
    "Bagama orollari": "Karib dengizida, sayyohlik maskani, poytaxti Nassau.",
    "Bahrayn": "Fors koʻrfazidagi orol, poytaxti Manama.",
    "Bangladesh": "Janubiy Osiyoda, Ganges deltasi, poytaxti Dakka.",
    "Barbados": "Karib dengizida, reggae va plyajlar, poytaxti Bridjtaun.",
    "Belarus": "Yevropada, keng oʻrmonlar, poytaxti Minsk.",
    "Belgiya": "Yevropada, shokolad va vafli, poytaxti Bryussel.",
    "Beliz": "Markaziy Amerikada, Marjon riflari, poytaxti Belmopan.",
    "Benin": "Gʻarbiy Afrikada, Vudu dini, poytaxti Porto-Novo.",
    "Butan": "Himolaylarda, baxt indeksi, poytaxti Thimphu.",
    "Boliviya": "Janubiy Amerikada, And togʻlari, poytaxti Sukre.",
    "Bosniya va Gertsegovina": "Balkanda, tarixiy koʻpriklar, poytaxti Sarayevo.",
    "Botsvana": "Janubiy Afrikada, Okavango deltasi, poytaxti Gaborone.",
    "Braziliya": "Janubiy Amerikada, Amazon oʻrmonlari, poytaxti Brazilia.",
    "Bruney": "Janubi-Sharqiy Osiyoda, neft boyliklari, poytaxti Bandar Seri Begavon.",
    "Bolgariya": "Yevropada, Qora dengiz sohilida, poytaxti Sofiya.",
    "Burkina Faso": "Gʻarbiy Afrikada, savanna, poytaxti Uagadugu.",
    "Burundi": "Sharqiy Afrikada, Tanganyika koʻli, poytaxti Gitega.",
    "Kabo Verde": "Atlantika okeanida, orollar, poytaxti Praya.",
    "Kambodja": "Janubi-Sharqiy Osiyoda, Angkor Vat, poytaxti Pnompen.",
    "Kamerun": "Markaziy Afrikada, 'Afrikaning miniatyurasi', poytaxti Yaunde.",
    "Kanada": "Shimoliy Amerikada, xokkey, poytaxti Ottava.",
    "Markaziy Afrika Respublikasi": "Afrika markazida, resurslar, poytaxti Bangui.",
    "Chad": "Afrikada, Saxara choʻli, poytaxti Njamena.",
    "Chili": "Janubiy Amerikada, uzun sohil, poytaxti Santyago.",
    "Xitoy": "Osiyoda, Buyuk Xitoy devori, poytaxti Pekin.",
    "Kolumbiya": "Janubiy Amerikada, kofe, poytaxti Bogota.",
    "Komor orollari": "Hind okeanida, vanil, poytaxti Moroni.",
    "Kongo Demokratik Respublikasi": "Afrikada, Kongo daryosi, poytaxti Kinshasa.",
    "Kongo Respublikasi": "Markaziy Afrikada, tropik oʻrmonlar, poytaxti Brazzavil.",
    "Kosta Rika": "Markaziy Amerikada, ekoturizm, poytaxti San-Xose.",
    "Xorvatiya": "Yevropada, Adriatik orollari, poytaxti Zagreb.",
    "Kuba": "Karib dengizida, salsa raqsi, poytaxti Gavana.",
    "Qibris": "Oʻrta yer dengizida, ikkiga boʻlingan, poytaxti Nikosiya.",
    "Chexiya": "Yevropada, pivo va qalʼalar, poytaxti Praga.",
    "Daniya": "Yevropada, Vikinglar merosi, poytaxti Kopengagen.",
    "Jibuti": "Afrika shoxida, Qizil dengiz, poytaxti Jibuti.",
    "Dominika": "Karib dengizida, vulqonlar, poytaxti Rozo.",
    "Dominikan Respublikasi": "Karib dengizida, merenge, poytaxti Santo-Domingo.",
    "Ekvador": "Janubiy Amerikada, Galapagos, poytaxti Kito.",
    "Misr": "Afrikada, Nil daryosi, poytaxti Qohira.",
    "Salvador": "Markaziy Amerikada, kichik davlat, poytaxti San-Salvador.",
    "Ekvatorial Gvineya": "Afrikada, neft resurslari, poytaxti Malabo.",
    "Eritreya": "Afrika shoxida, Qizil dengiz, poytaxti Asmara.",
    "Estoniya": "Yevropada, raqamli innovatsiyalar, poytaxti Tallin.",
    "Esvatini": "Janubiy Afrikada, monarxiya, poytaxti Mbabane.",
    "Efiopiya": "Afrikada, qahva vatani, poytaxti Addis-Abeba.",
    "Fiji": "Tinch okeanida, marjon riflari, poytaxti Suva.",
    "Finlandiya": "Yevropada, koʻllar va sauna, poytaxti Xelsinki.",
    "Fransiya": "Yevropada, Eyfel minorasi, poytaxti Parij.",
    "Gabon": "Afrikada, tropik oʻrmonlar, poytaxti Librevil.",
    "Gambiya": "Afrikada, kichik materik davlati, poytaxti Banjul.",
    "Gruziya": "Kavkazda, sharob anʼanalari, poytaxti Tbilisi.",
    "Germaniya": "Yevropada, Oktoberfest, poytaxti Berlin.",
    "Gana": "Gʻarbiy Afrikada, oltin va kakao, poytaxti Akkra.",
    "Gretsiya": "Yevropada, qadimiy xarobalar, poytaxti Afina.",
    "Grenada": "Karib dengizida, muskat yongʻogʻi, poytaxti Sent-Jorj.",
    "Gvatemala": "Markaziy Amerikada, Maya xarobalari, poytaxti Gvatemala Siti.",
    "Gvineya": "Gʻarbiy Afrikada, mineral resurslar, poytaxti Konakri.",
    "Gvineya-Bisau": "Gʻarbiy Afrikada, kaju yongʻogʻi, poytaxti Bisau.",
    "Gayana": "Janubiy Amerikada, Karib sohilida, poytaxti Jorjtaun.",
    "Gaiti": "Karib dengizida, kreol madaniyati, poytaxti Port-o-Prens.",
    "Gonduras": "Markaziy Amerikada, banan eksporti, poytaxti Tegusigalpa.",
    "Vengriya": "Yevropada, termal buloqlar, poytaxti Budapesht.",
    "Islandiya": "Yevropada, vulqonlar, poytaxti Reykyavik.",
    "Hindiston": "Janubiy Osiyoda, Taj Mahal, poytaxti Yangi Dehli.",
    "Indoneziya": "Janubi-Sharqiy Osiyoda, minglab orollar, poytaxti Jakarta.",
    "Eron": "Osiyoda, Fors madaniyati, poytaxti Tehron.",
    "Iroq": "Yaqin Sharqda, Mesopotamiya, poytaxti Bagʻdod.",
    "Irlandiya": "Yevropada, yashil landshaftlar, poytaxti Dublin.",
    "Isroil": "Yaqin Sharqda, diniy joylar, poytaxti Tel Aviv.",
    "Italiya": "Yevropada, Rim xarobalari, poytaxti Rim.",
    "Yamayka": "Karib dengizida, reggae musiqa, poytaxti Kingston.",
    "Yaponiya": "Osiyoda, sushi va samuraylar, poytaxti Tokio.",
    "Iordaniya": "Yaqin Sharqda, Petra shahri, poytaxti Ammon.",
    "Qozogʻiston": "Markaziy Osiyoda, keng dashtlar, poytaxti Astana.",
    "Keniya": "Sharqiy Afrikada, safari, poytaxti Nayrobi.",
    "Kiribati": "Tinch okeanida, kichik orollar, poytaxti Tarava.",
    "Kuvayt": "Fors koʻrfazida, neft iqtisodiyoti, poytaxti Kuvayt Siti.",
    "Qirgʻiziston": "Markaziy Osiyoda, togʻli landshaftlar, poytaxti Bishkek.",
    "Laos": "Janubi-Sharqiy Osiyoda, Mekong daryosi, poytaxti Vientian.",
    "Latviya": "Yevropada, Boltiqboʻyi, poytaxti Riga.",
    "Livan": "Yaqin Sharqda, Finikiya merosi, poytaxti Bayrut.",
    "Lesoto": "Janubiy Afrikada, togʻli mamlakat, poytaxti Maseru.",
    "Liberiya": "Gʻarbiy Afrikada, AQSh muhojirlari, poytaxti Monroviya.",
    "Liviya": "Shimoliy Afrikada, Saxara choʻli, poytaxti Tripoli.",
    "Lixtenshteyn": "Yevropada, kichik knyazlik, poytaxti Vaduz.",
    "Litva": "Yevropada, Boltiqboʻyi, poytaxti Vilnyus.",
    "Lyuksemburg": "Yevropada, moliyaviy markaz, poytaxti Lyuksemburg.",
    "Madagaskar": "Afrikada, lemurlar vatani, poytaxti Antananarivo.",
    "Malavi": "Sharqiy Afrikada, Malavi koʻli, poytaxti Lilongve.",
    "Malayziya": "Janubi-Sharqiy Osiyoda, Petronas minoralari, poytaxti Kuala-Lumpur.",
    "Maldiv orollari": "Hind okeanida, dam olish maskanlari, poytaxti Male.",
    "Mali": "Gʻarbiy Afrikada, Timbuktu, poytaxti Bamako.",
    "Malta": "Oʻrta yer dengizida, tarixiy qalʼalar, poytaxti Valletta.",
    "Marshall orollari": "Tinch okeanida, kichik orollar, poytaxti Majuro.",
    "Mavritaniya": "Afrikada, Saxara choʻli, poytaxti Nuakshot.",
    "Mavrikiy": "Hind okeanida, koʻp madaniyatli, poytaxti Port-Lui.",
    "Meksika": "Shimoliy Amerikada, Maya xarobalari, poytaxti Mexiko Siti.",
    "Mikroneziya": "Tinch okeanida, orollar federatsiyasi, poytaxti Palikir.",
    "Moldova": "Yevropada, sharob ishlab chiqarish, poytaxti Kishinyov.",
    "Monako": "Yevropada, kazinolar, poytaxti Monako.",
    "Moʻgʻuliston": "Osiyoda, keng dashtlar, poytaxti Ulan-Bator.",
    "Chernogoriya": "Balkanda, Kotor koʻrfazi, poytaxti Podgoritsa.",
    "Marokash": "Afrikada, Atlas togʻlari, poytaxti Rabat.",
    "Mozambik": "Sharqiy Afrikada, Hind okeani sohilida, poytaxti Maputo.",
    "Myanma": "Janubi-Sharqiy Osiyoda, buddist pagodalar, poytaxti Naypyido.",
    "Namibiya": "Janubiy Afrikada, Namib choʻli, poytaxti Vindhuk.",
    "Nauru": "Tinch okeanida, kichik orol, poytaxti Yaren.",
    "Nepal": "Osiyoda, Everest choʻqqisi, poytaxti Katmandu.",
    "Niderlandiya": "Yevropada, lola va shamol tegirmonlari, poytaxti Amsterdam.",
    "Yangi Zelandiya": "Okeaniyada, Maori madaniyati, poytaxti Vellington.",
    "Nikaragua": "Markaziy Amerikada, vulqonlar, poytaxti Managua.",
    "Niger": "Afrikada, Saxara choʻli, poytaxti Niamey.",
    "Nigeriya": "Afrikada, koʻp aholiga ega, poytaxti Abuja.",
    "Shimoliy Koreya": "Osiyoda, izolyatsiya qilingan, poytaxti Pxenyan.",
    "Shimoliy Makedoniya": "Balkanda, Ohrid koʻli, poytaxti Skopye.",
    "Norvegiya": "Yevropada, fyordlar, poytaxti Oslo.",
    "Ummon": "Yaqin Sharqda, Arab yarim oroli, poytaxti Maskat.",
    "Pokiston": "Janubiy Osiyoda, Indus daryosi, poytaxti Islomobod.",
    "Palau": "Tinch okeanida, marjon riflari, poytaxti Ngerulmud.",
    "Falastin": "Yaqin Sharqda, diniy joylar, poytaxti Sharqiy Quddus.",
    "Panama": "Markaziy Amerikada, Panama kanali, poytaxti Panama Siti.",
    "Papua Yangi Gvineya": "Okeaniyada, koʻp tillar, poytaxti Port-Moresbi.",
    "Paragvay": "Janubiy Amerikada, Guarani madaniyati, poytaxti Asunsion.",
    "Peru": "Janubiy Amerikada, Machu Pikchu, poytaxti Lima.",
    "Filippin": "Janubi-Sharqiy Osiyoda, minglab orollar, poytaxti Manila.",
    "Polsha": "Yevropada, Amber yoʻli, poytaxti Varshava.",
    "Portugaliya": "Yevropada, fado musiqasi, poytaxti Lissabon.",
    "Qatar": "Fors koʻrfazida, zamonaviy arxitektura, poytaxti Doha.",
    "Ruminiya": "Yevropada, Drakula afsonasi, poytaxti Buxarest.",
    "Rossiya": "Yevropa va Osiyoda, eng katta maydon, poytaxti Moskva.",
    "Ruanda": "Sharqiy Afrikada, ming tepaliklar, poytaxti Kigali.",
    "Sent Kitts va Nevis": "Karib dengizida, kichik orollar, poytaxti Baster.",
    "Sent Lusiya": "Karib dengizida, Piton togʻlari, poytaxti Kastri.",
    "Sent Vinsent va Grenadinlar": "Karib dengizida, yelkanli sport, poytaxti Kingstaun.",
    "Samoa": "Tinch okeanida, Polineziya madaniyati, poytaxti Apia.",
    "San Marino": "Yevropada, qadimiy respublika, poytaxti San Marino.",
    "San-Tome va Prinsipi": "Afrikada, Gvineya koʻrfazi, poytaxti San-Tome.",
    "Saudiya Arabistoni": "Yaqin Sharqda, Makka va Madina, poytaxti Riyod.",
    "Senegal": "Gʻarbiy Afrikada, Dakar rallisi, poytaxti Dakar.",
    "Serbiya": "Balkanda, pravoslav cherkovlari, poytaxti Belgrad.",
    "Seyshell orollari": "Hind okeanida, plyajlar, poytaxti Viktoriya.",
    "Syerra Leone": "Gʻarbiy Afrikada, olmos konlari, poytaxti Fritaun.",
    "Singapur": "Janubi-Sharqiy Osiyoda, shahar-davlat, poytaxti Singapur.",
    "Slovakiya": "Yevropada, Karpat togʻlari, poytaxti Bratislava.",
    "Sloveniya": "Yevropada, Bled koʻli, poytaxti Lyublyana.",
    "Solomon orollari": "Tinch okeanida, urush yodgorliklari, poytaxti Honiara.",
    "Somali": "Afrika shoxida, Hind okeani, poytaxti Mogadishu.",
    "Janubiy Afrika": "Afrikada, Nelson Mandela, poytaxti Pretoriya.",
    "Janubiy Koreya": "Osiyoda, K-pop, poytaxti Seul.",
    "Janubiy Sudan": "Afrikada, eng yosh davlat, poytaxti Juba.",
    "Ispaniya": "Yevropada, flamenko, poytaxti Madrid.",
    "Shri Lanka": "Hind okeanida, choy plantatsiyalari, poytaxti Shri Jayavardenepura Kotte.",
    "Sudan": "Afrikada, Nil daryosi, poytaxti Xartum.",
    "Surinam": "Janubiy Amerikada, koʻp madaniyatli, poytaxti Paramaribo.",
    "Shvetsiya": "Yevropada, IKEA va Nobel, poytaxti Stokgolm.",
    "Shveytsariya": "Yevropada, Alp togʻlari, poytaxti Bern.",
    "Suriya": "Yaqin Sharqda, qadimiy Damashq, poytaxti Damashq.",
    "Tayvan": "Osiyoda, tungi bozorlar, poytaxti Taypey.",
    "Tojikiston": "Markaziy Osiyoda, Pamir togʻlari, poytaxti Dushanbe.",
    "Tanzaniya": "Sharqiy Afrikada, Zanzibar, poytaxti Dodoma.",
    "Tailand": "Janubi-Sharqiy Osiyoda, buddist ibodatxonalari, poytaxti Bangkok.",
    "Sharqiy Timor": "Janubi-Sharqiy Osiyoda, yosh davlat, poytaxti Dili.",
    "Togo": "Gʻarbiy Afrikada, Atlantika sohilida, poytaxti Lome.",
    "Tonga": "Tinch okeanida, Polineziya qirolligi, poytaxti Nukualofa.",
    "Trinidad va Tobago": "Karib dengizida, karnaval, poytaxti Port-of-Speyn.",
    "Tunis": "Shimoliy Afrikada, Karfagen xarobalari, poytaxti Tunis.",
    "Turkiya": "Yevropa va Osiyoda, Bosfor boʻgʻozi, poytaxti Anqara.",
    "Turkmaniston": "Markaziy Osiyoda, gaz resurslari, poytaxti Ashxobod.",
    "Tuvalu": "Tinch okeanida, kichik davlat, poytaxti Funafuti.",
    "Uganda": "Sharqiy Afrikada, Viktoriya koʻli, poytaxti Kampala.",
    "Ukraina": "Yevropada, keng dashtlar, poytaxti Kiyev.",
    "Birlashgan Arab Amirliklari": "Yaqin Sharqda, Dubay, poytaxti Abu-Dabi.",
    "Buyuk Britaniya": "Yevropada, monarxiya, poytaxti London.",
    "Amerika Qoʻshma Shtatlari": "Shimoliy Amerikada, Gollivud, poytaxti Vashington, D.C.",
    "Urugvay": "Janubiy Amerikada, futbol, poytaxti Montevideo.",
    "Oʻzbekiston": "Markaziy Osiyoda, Ipak yoʻli, poytaxti Toshkent.",
    "Vanuatu": "Tinch okeanida, vulqonlar, poytaxti Port-Vila.",
    "Vatikan": "Yevropada, Katolik cherkovi, poytaxti Vatikan Siti.",
    "Venesuela": "Janubiy Amerikada, neft resurslari, poytaxti Karakas.",
    "Vyetnam": "Janubi-Sharqiy Osiyoda, Halong koʻrfazi, poytaxti Xanoy.",
    "Yaman": "Yaqin Sharqda, qadimiy shaharlar, poytaxti Sano.",
    "Zambiya": "Janubiy Afrikada, Viktoriya sharsharasi, poytaxti Lusaka.",
    "Zimbabve": "Janubiy Afrikada, Buyuk Zimbabve, poytaxti Harare.",
}

# ISO 3166-1 alpha-2 codes for flag emoji generation
COUNTRY_ISO2: dict[str, str] = {
    "Afgʻoniston": "AF", "Albaniya": "AL", "Jazoir": "DZ", "Andorra": "AD",
    "Angola": "AO", "Antigua va Barbuda": "AG", "Argentina": "AR", "Armaniston": "AM",
    "Avstraliya": "AU", "Avstriya": "AT", "Ozarbayjon": "AZ", "Bagama orollari": "BS",
    "Bahrayn": "BH", "Bangladesh": "BD", "Barbados": "BB", "Belarus": "BY",
    "Belgiya": "BE", "Beliz": "BZ", "Benin": "BJ", "Butan": "BT",
    "Boliviya": "BO", "Bosniya va Gertsegovina": "BA", "Botsvana": "BW",
    "Braziliya": "BR", "Bruney": "BN", "Bolgariya": "BG", "Burkina Faso": "BF",
    "Burundi": "BI", "Kabo Verde": "CV", "Kambodja": "KH", "Kamerun": "CM",
    "Kanada": "CA", "Markaziy Afrika Respublikasi": "CF", "Chad": "TD",
    "Chili": "CL", "Xitoy": "CN", "Kolumbiya": "CO", "Komor orollari": "KM",
    "Kongo Demokratik Respublikasi": "CD", "Kongo Respublikasi": "CG",
    "Kosta Rika": "CR", "Xorvatiya": "HR", "Kuba": "CU", "Qibris": "CY",
    "Chexiya": "CZ", "Daniya": "DK", "Jibuti": "DJ", "Dominika": "DM",
    "Dominikan Respublikasi": "DO", "Ekvador": "EC", "Misr": "EG",
    "Salvador": "SV", "Ekvatorial Gvineya": "GQ", "Eritreya": "ER",
    "Estoniya": "EE", "Esvatini": "SZ", "Efiopiya": "ET", "Fiji": "FJ",
    "Finlandiya": "FI", "Fransiya": "FR", "Gabon": "GA", "Gambiya": "GM",
    "Gruziya": "GE", "Germaniya": "DE", "Gana": "GH", "Gretsiya": "GR",
    "Grenada": "GD", "Gvatemala": "GT", "Gvineya": "GN", "Gvineya-Bisau": "GW",
    "Gayana": "GY", "Gaiti": "HT", "Gonduras": "HN", "Vengriya": "HU",
    "Islandiya": "IS", "Hindiston": "IN", "Indoneziya": "ID", "Eron": "IR",
    "Iroq": "IQ", "Irlandiya": "IE", "Isroil": "IL", "Italiya": "IT",
    "Yamayka": "JM", "Yaponiya": "JP", "Iordaniya": "JO", "Qozogʻiston": "KZ",
    "Keniya": "KE", "Kiribati": "KI", "Kuvayt": "KW", "Qirgʻiziston": "KG",
    "Laos": "LA", "Latviya": "LV", "Livan": "LB", "Lesoto": "LS",
    "Liberiya": "LR", "Liviya": "LY", "Lixtenshteyn": "LI", "Litva": "LT",
    "Lyuksemburg": "LU", "Madagaskar": "MG", "Malavi": "MW", "Malayziya": "MY",
    "Maldiv orollari": "MV", "Mali": "ML", "Malta": "MT",
    "Marshall orollari": "MH", "Mavritaniya": "MR", "Mavrikiy": "MU",
    "Meksika": "MX", "Mikroneziya": "FM", "Moldova": "MD", "Monako": "MC",
    "Moʻgʻuliston": "MN", "Chernogoriya": "ME", "Marokash": "MA",
    "Mozambik": "MZ", "Myanma": "MM", "Namibiya": "NA", "Nauru": "NR",
    "Nepal": "NP", "Niderlandiya": "NL", "Yangi Zelandiya": "NZ",
    "Nikaragua": "NI", "Niger": "NE", "Nigeriya": "NG", "Shimoliy Koreya": "KP",
    "Shimoliy Makedoniya": "MK", "Norvegiya": "NO", "Ummon": "OM",
    "Pokiston": "PK", "Palau": "PW", "Falastin": "PS", "Panama": "PA",
    "Papua Yangi Gvineya": "PG", "Paragvay": "PY", "Peru": "PE",
    "Filippin": "PH", "Polsha": "PL", "Portugaliya": "PT", "Qatar": "QA",
    "Ruminiya": "RO", "Rossiya": "RU", "Ruanda": "RW",
    "Sent Kitts va Nevis": "KN", "Sent Lusiya": "LC",
    "Sent Vinsent va Grenadinlar": "VC", "Samoa": "WS", "San Marino": "SM",
    "San-Tome va Prinsipi": "ST", "Saudiya Arabistoni": "SA", "Senegal": "SN",
    "Serbiya": "RS", "Seyshell orollari": "SC", "Syerra Leone": "SL",
    "Singapur": "SG", "Slovakiya": "SK", "Sloveniya": "SI",
    "Solomon orollari": "SB", "Somali": "SO", "Janubiy Afrika": "ZA",
    "Janubiy Koreya": "KR", "Janubiy Sudan": "SS", "Ispaniya": "ES",
    "Shri Lanka": "LK", "Sudan": "SD", "Surinam": "SR", "Shvetsiya": "SE",
    "Shveytsariya": "CH", "Suriya": "SY", "Tayvan": "TW", "Tojikiston": "TJ",
    "Tanzaniya": "TZ", "Tailand": "TH", "Sharqiy Timor": "TL", "Togo": "TG",
    "Tonga": "TO", "Trinidad va Tobago": "TT", "Tunis": "TN", "Turkiya": "TR",
    "Turkmaniston": "TM", "Tuvalu": "TV", "Uganda": "UG", "Ukraina": "UA",
    "Birlashgan Arab Amirliklari": "AE", "Buyuk Britaniya": "GB",
    "Amerika Qoʻshma Shtatlari": "US", "Urugvay": "UY", "Oʻzbekiston": "UZ",
    "Vanuatu": "VU", "Vatikan": "VA", "Venesuela": "VE", "Vyetnam": "VN",
    "Yaman": "YE", "Zambiya": "ZM", "Zimbabve": "ZW",
}


def _flag_emoji(iso2: str) -> str:
    return ''.join(chr(0x1F1E6 + ord(c) - ord('A')) for c in iso2.upper())


COUNTRY_FLAGS: dict[str, str] = {uz: _flag_emoji(iso2) for uz, iso2 in COUNTRY_ISO2.items()}

COUNTRY_CONTINENTS: dict[str, str] = {
    # Africa
    "Jazoir": "africa", "Angola": "africa", "Benin": "africa",
    "Botsvana": "africa", "Burkina Faso": "africa", "Burundi": "africa",
    "Kabo Verde": "africa", "Kamerun": "africa", "Markaziy Afrika Respublikasi": "africa",
    "Chad": "africa", "Komor orollari": "africa",
    "Kongo Demokratik Respublikasi": "africa", "Kongo Respublikasi": "africa",
    "Jibuti": "africa", "Misr": "africa", "Ekvatorial Gvineya": "africa",
    "Eritreya": "africa", "Esvatini": "africa", "Efiopiya": "africa",
    "Gabon": "africa", "Gambiya": "africa", "Gana": "africa",
    "Gvineya": "africa", "Gvineya-Bisau": "africa", "Keniya": "africa",
    "Lesoto": "africa", "Liberiya": "africa", "Liviya": "africa",
    "Madagaskar": "africa", "Malavi": "africa", "Mali": "africa",
    "Mavritaniya": "africa", "Mavrikiy": "africa", "Marokash": "africa",
    "Mozambik": "africa", "Namibiya": "africa", "Niger": "africa",
    "Nigeriya": "africa", "Ruanda": "africa", "San-Tome va Prinsipi": "africa",
    "Senegal": "africa", "Seyshell orollari": "africa", "Syerra Leone": "africa",
    "Somali": "africa", "Janubiy Afrika": "africa", "Janubiy Sudan": "africa",
    "Sudan": "africa", "Tanzaniya": "africa", "Togo": "africa",
    "Tunis": "africa", "Uganda": "africa", "Zambiya": "africa",
    "Zimbabve": "africa",
    # Asia
    "Afgʻoniston": "asia", "Armaniston": "asia", "Ozarbayjon": "asia",
    "Bahrayn": "asia", "Bangladesh": "asia", "Butan": "asia",
    "Bruney": "asia", "Kambodja": "asia", "Xitoy": "asia",
    "Qibris": "asia", "Gruziya": "asia", "Hindiston": "asia",
    "Indoneziya": "asia", "Eron": "asia", "Iroq": "asia",
    "Isroil": "asia", "Yaponiya": "asia", "Iordaniya": "asia",
    "Qozogʻiston": "asia", "Kuvayt": "asia", "Qirgʻiziston": "asia",
    "Laos": "asia", "Livan": "asia", "Malayziya": "asia",
    "Maldiv orollari": "asia", "Moʻgʻuliston": "asia", "Myanma": "asia",
    "Nepal": "asia", "Shimoliy Koreya": "asia", "Ummon": "asia",
    "Pokiston": "asia", "Falastin": "asia", "Filippin": "asia",
    "Qatar": "asia", "Saudiya Arabistoni": "asia", "Singapur": "asia",
    "Janubiy Koreya": "asia", "Shri Lanka": "asia", "Suriya": "asia",
    "Tayvan": "asia", "Tojikiston": "asia", "Tailand": "asia",
    "Sharqiy Timor": "asia", "Turkiya": "asia", "Turkmaniston": "asia",
    "Birlashgan Arab Amirliklari": "asia", "Oʻzbekiston": "asia",
    "Vyetnam": "asia", "Yaman": "asia",
    # Europe
    "Albaniya": "europe", "Andorra": "europe", "Avstriya": "europe",
    "Belarus": "europe", "Belgiya": "europe", "Bosniya va Gertsegovina": "europe",
    "Bolgariya": "europe", "Xorvatiya": "europe", "Chexiya": "europe",
    "Daniya": "europe", "Estoniya": "europe", "Finlandiya": "europe",
    "Fransiya": "europe", "Germaniya": "europe", "Gretsiya": "europe",
    "Vengriya": "europe", "Islandiya": "europe", "Irlandiya": "europe",
    "Italiya": "europe", "Latviya": "europe", "Lixtenshteyn": "europe",
    "Litva": "europe", "Lyuksemburg": "europe", "Malta": "europe",
    "Moldova": "europe", "Monako": "europe", "Chernogoriya": "europe",
    "Niderlandiya": "europe", "Shimoliy Makedoniya": "europe",
    "Norvegiya": "europe", "Polsha": "europe", "Portugaliya": "europe",
    "Ruminiya": "europe", "Rossiya": "europe", "San Marino": "europe",
    "Serbiya": "europe", "Slovakiya": "europe", "Sloveniya": "europe",
    "Ispaniya": "europe", "Shvetsiya": "europe", "Shveytsariya": "europe",
    "Ukraina": "europe", "Buyuk Britaniya": "europe", "Vatikan": "europe",
    # North America
    "Antigua va Barbuda": "north_america", "Bagama orollari": "north_america",
    "Barbados": "north_america", "Beliz": "north_america",
    "Kanada": "north_america", "Kosta Rika": "north_america",
    "Kuba": "north_america", "Dominika": "north_america",
    "Dominikan Respublikasi": "north_america", "Salvador": "north_america",
    "Grenada": "north_america", "Gvatemala": "north_america",
    "Gaiti": "north_america", "Gonduras": "north_america",
    "Yamayka": "north_america", "Meksika": "north_america",
    "Nikaragua": "north_america", "Panama": "north_america",
    "Sent Kitts va Nevis": "north_america", "Sent Lusiya": "north_america",
    "Sent Vinsent va Grenadinlar": "north_america",
    "Trinidad va Tobago": "north_america",
    "Amerika Qoʻshma Shtatlari": "north_america",
    # South America
    "Argentina": "south_america", "Boliviya": "south_america",
    "Braziliya": "south_america", "Chili": "south_america",
    "Kolumbiya": "south_america", "Ekvador": "south_america",
    "Gayana": "south_america", "Paragvay": "south_america",
    "Peru": "south_america", "Surinam": "south_america",
    "Urugvay": "south_america", "Venesuela": "south_america",
    # Oceania
    "Avstraliya": "oceania", "Fiji": "oceania", "Kiribati": "oceania",
    "Marshall orollari": "oceania", "Mikroneziya": "oceania",
    "Nauru": "oceania", "Yangi Zelandiya": "oceania", "Palau": "oceania",
    "Papua Yangi Gvineya": "oceania", "Samoa": "oceania",
    "Solomon orollari": "oceania", "Tonga": "oceania",
    "Tuvalu": "oceania", "Vanuatu": "oceania",
}

# (currency_english_name, ISO-4217 code)
COUNTRY_CURRENCIES: dict[str, tuple[str, str]] = {
    "Afgʻoniston": ("Afghan Afghani", "AFN"),
    "Albaniya": ("Albanian Lek", "ALL"),
    "Jazoir": ("Algerian Dinar", "DZD"),
    "Andorra": ("Euro", "EUR"),
    "Angola": ("Angolan Kwanza", "AOA"),
    "Antigua va Barbuda": ("Eastern Caribbean Dollar", "XCD"),
    "Argentina": ("Argentine Peso", "ARS"),
    "Armaniston": ("Armenian Dram", "AMD"),
    "Avstraliya": ("Australian Dollar", "AUD"),
    "Avstriya": ("Euro", "EUR"),
    "Ozarbayjon": ("Azerbaijani Manat", "AZN"),
    "Bagama orollari": ("Bahamian Dollar", "BSD"),
    "Bahrayn": ("Bahraini Dinar", "BHD"),
    "Bangladesh": ("Bangladeshi Taka", "BDT"),
    "Barbados": ("Barbadian Dollar", "BBD"),
    "Belarus": ("Belarusian Ruble", "BYN"),
    "Belgiya": ("Euro", "EUR"),
    "Beliz": ("Belize Dollar", "BZD"),
    "Benin": ("West African CFA Franc", "XOF"),
    "Butan": ("Bhutanese Ngultrum", "BTN"),
    "Boliviya": ("Bolivian Boliviano", "BOB"),
    "Bosniya va Gertsegovina": ("Convertible Mark", "BAM"),
    "Botsvana": ("Botswana Pula", "BWP"),
    "Braziliya": ("Brazilian Real", "BRL"),
    "Bruney": ("Brunei Dollar", "BND"),
    "Bolgariya": ("Bulgarian Lev", "BGN"),
    "Burkina Faso": ("West African CFA Franc", "XOF"),
    "Burundi": ("Burundian Franc", "BIF"),
    "Kabo Verde": ("Cape Verdean Escudo", "CVE"),
    "Kambodja": ("Cambodian Riel", "KHR"),
    "Kamerun": ("Central African CFA Franc", "XAF"),
    "Kanada": ("Canadian Dollar", "CAD"),
    "Markaziy Afrika Respublikasi": ("Central African CFA Franc", "XAF"),
    "Chad": ("Central African CFA Franc", "XAF"),
    "Chili": ("Chilean Peso", "CLP"),
    "Xitoy": ("Chinese Yuan", "CNY"),
    "Kolumbiya": ("Colombian Peso", "COP"),
    "Komor orollari": ("Comorian Franc", "KMF"),
    "Kongo Demokratik Respublikasi": ("Congolese Franc", "CDF"),
    "Kongo Respublikasi": ("Central African CFA Franc", "XAF"),
    "Kosta Rika": ("Costa Rican Colón", "CRC"),
    "Xorvatiya": ("Euro", "EUR"),
    "Kuba": ("Cuban Peso", "CUP"),
    "Qibris": ("Euro", "EUR"),
    "Chexiya": ("Czech Koruna", "CZK"),
    "Daniya": ("Danish Krone", "DKK"),
    "Jibuti": ("Djiboutian Franc", "DJF"),
    "Dominika": ("Eastern Caribbean Dollar", "XCD"),
    "Dominikan Respublikasi": ("Dominican Peso", "DOP"),
    "Ekvador": ("US Dollar", "USD"),
    "Misr": ("Egyptian Pound", "EGP"),
    "Salvador": ("US Dollar", "USD"),
    "Ekvatorial Gvineya": ("Central African CFA Franc", "XAF"),
    "Eritreya": ("Eritrean Nakfa", "ERN"),
    "Estoniya": ("Euro", "EUR"),
    "Esvatini": ("Swazi Lilangeni", "SZL"),
    "Efiopiya": ("Ethiopian Birr", "ETB"),
    "Fiji": ("Fijian Dollar", "FJD"),
    "Finlandiya": ("Euro", "EUR"),
    "Fransiya": ("Euro", "EUR"),
    "Gabon": ("Central African CFA Franc", "XAF"),
    "Gambiya": ("Gambian Dalasi", "GMD"),
    "Gruziya": ("Georgian Lari", "GEL"),
    "Germaniya": ("Euro", "EUR"),
    "Gana": ("Ghanaian Cedi", "GHS"),
    "Gretsiya": ("Euro", "EUR"),
    "Grenada": ("Eastern Caribbean Dollar", "XCD"),
    "Gvatemala": ("Guatemalan Quetzal", "GTQ"),
    "Gvineya": ("Guinean Franc", "GNF"),
    "Gvineya-Bisau": ("West African CFA Franc", "XOF"),
    "Gayana": ("Guyanese Dollar", "GYD"),
    "Gaiti": ("Haitian Gourde", "HTG"),
    "Gonduras": ("Honduran Lempira", "HNL"),
    "Vengriya": ("Hungarian Forint", "HUF"),
    "Islandiya": ("Icelandic Króna", "ISK"),
    "Hindiston": ("Indian Rupee", "INR"),
    "Indoneziya": ("Indonesian Rupiah", "IDR"),
    "Eron": ("Iranian Rial", "IRR"),
    "Iroq": ("Iraqi Dinar", "IQD"),
    "Irlandiya": ("Euro", "EUR"),
    "Isroil": ("Israeli Shekel", "ILS"),
    "Italiya": ("Euro", "EUR"),
    "Yamayka": ("Jamaican Dollar", "JMD"),
    "Yaponiya": ("Japanese Yen", "JPY"),
    "Iordaniya": ("Jordanian Dinar", "JOD"),
    "Qozogʻiston": ("Kazakhstani Tenge", "KZT"),
    "Keniya": ("Kenyan Shilling", "KES"),
    "Kiribati": ("Australian Dollar", "AUD"),
    "Kuvayt": ("Kuwaiti Dinar", "KWD"),
    "Qirgʻiziston": ("Kyrgyzstani Som", "KGS"),
    "Laos": ("Lao Kip", "LAK"),
    "Latviya": ("Euro", "EUR"),
    "Livan": ("Lebanese Pound", "LBP"),
    "Lesoto": ("Lesotho Loti", "LSL"),
    "Liberiya": ("Liberian Dollar", "LRD"),
    "Liviya": ("Libyan Dinar", "LYD"),
    "Lixtenshteyn": ("Swiss Franc", "CHF"),
    "Litva": ("Euro", "EUR"),
    "Lyuksemburg": ("Euro", "EUR"),
    "Madagaskar": ("Malagasy Ariary", "MGA"),
    "Malavi": ("Malawian Kwacha", "MWK"),
    "Malayziya": ("Malaysian Ringgit", "MYR"),
    "Maldiv orollari": ("Maldivian Rufiyaa", "MVR"),
    "Mali": ("West African CFA Franc", "XOF"),
    "Malta": ("Euro", "EUR"),
    "Marshall orollari": ("US Dollar", "USD"),
    "Mavritaniya": ("Mauritanian Ouguiya", "MRU"),
    "Mavrikiy": ("Mauritian Rupee", "MUR"),
    "Meksika": ("Mexican Peso", "MXN"),
    "Mikroneziya": ("US Dollar", "USD"),
    "Moldova": ("Moldovan Leu", "MDL"),
    "Monako": ("Euro", "EUR"),
    "Moʻgʻuliston": ("Mongolian Tögrög", "MNT"),
    "Chernogoriya": ("Euro", "EUR"),
    "Marokash": ("Moroccan Dirham", "MAD"),
    "Mozambik": ("Mozambican Metical", "MZN"),
    "Myanma": ("Myanmar Kyat", "MMK"),
    "Namibiya": ("Namibian Dollar", "NAD"),
    "Nauru": ("Australian Dollar", "AUD"),
    "Nepal": ("Nepalese Rupee", "NPR"),
    "Niderlandiya": ("Euro", "EUR"),
    "Yangi Zelandiya": ("New Zealand Dollar", "NZD"),
    "Nikaragua": ("Nicaraguan Córdoba", "NIO"),
    "Niger": ("West African CFA Franc", "XOF"),
    "Nigeriya": ("Nigerian Naira", "NGN"),
    "Shimoliy Koreya": ("North Korean Won", "KPW"),
    "Shimoliy Makedoniya": ("Macedonian Denar", "MKD"),
    "Norvegiya": ("Norwegian Krone", "NOK"),
    "Ummon": ("Omani Rial", "OMR"),
    "Pokiston": ("Pakistani Rupee", "PKR"),
    "Palau": ("US Dollar", "USD"),
    "Falastin": ("Israeli Shekel", "ILS"),
    "Panama": ("Panamanian Balboa", "PAB"),
    "Papua Yangi Gvineya": ("Papua New Guinean Kina", "PGK"),
    "Paragvay": ("Paraguayan Guaraní", "PYG"),
    "Peru": ("Peruvian Sol", "PEN"),
    "Filippin": ("Philippine Peso", "PHP"),
    "Polsha": ("Polish Złoty", "PLN"),
    "Portugaliya": ("Euro", "EUR"),
    "Qatar": ("Qatari Riyal", "QAR"),
    "Ruminiya": ("Romanian Leu", "RON"),
    "Rossiya": ("Russian Ruble", "RUB"),
    "Ruanda": ("Rwandan Franc", "RWF"),
    "Sent Kitts va Nevis": ("Eastern Caribbean Dollar", "XCD"),
    "Sent Lusiya": ("Eastern Caribbean Dollar", "XCD"),
    "Sent Vinsent va Grenadinlar": ("Eastern Caribbean Dollar", "XCD"),
    "Samoa": ("Samoan Tālā", "WST"),
    "San Marino": ("Euro", "EUR"),
    "San-Tome va Prinsipi": ("São Tomé Dobra", "STN"),
    "Saudiya Arabistoni": ("Saudi Riyal", "SAR"),
    "Senegal": ("West African CFA Franc", "XOF"),
    "Serbiya": ("Serbian Dinar", "RSD"),
    "Seyshell orollari": ("Seychellois Rupee", "SCR"),
    "Syerra Leone": ("Sierra Leonean Leone", "SLL"),
    "Singapur": ("Singapore Dollar", "SGD"),
    "Slovakiya": ("Euro", "EUR"),
    "Sloveniya": ("Euro", "EUR"),
    "Solomon orollari": ("Solomon Islands Dollar", "SBD"),
    "Somali": ("Somali Shilling", "SOS"),
    "Janubiy Afrika": ("South African Rand", "ZAR"),
    "Janubiy Koreya": ("South Korean Won", "KRW"),
    "Janubiy Sudan": ("South Sudanese Pound", "SSP"),
    "Ispaniya": ("Euro", "EUR"),
    "Shri Lanka": ("Sri Lankan Rupee", "LKR"),
    "Sudan": ("Sudanese Pound", "SDG"),
    "Surinam": ("Surinamese Dollar", "SRD"),
    "Shvetsiya": ("Swedish Krona", "SEK"),
    "Shveytsariya": ("Swiss Franc", "CHF"),
    "Suriya": ("Syrian Pound", "SYP"),
    "Tayvan": ("New Taiwan Dollar", "TWD"),
    "Tojikiston": ("Tajikistani Somoni", "TJS"),
    "Tanzaniya": ("Tanzanian Shilling", "TZS"),
    "Tailand": ("Thai Baht", "THB"),
    "Sharqiy Timor": ("US Dollar", "USD"),
    "Togo": ("West African CFA Franc", "XOF"),
    "Tonga": ("Tongan Paʻanga", "TOP"),
    "Trinidad va Tobago": ("Trinidad and Tobago Dollar", "TTD"),
    "Tunis": ("Tunisian Dinar", "TND"),
    "Turkiya": ("Turkish Lira", "TRY"),
    "Turkmaniston": ("Turkmenistani Manat", "TMT"),
    "Tuvalu": ("Australian Dollar", "AUD"),
    "Uganda": ("Ugandan Shilling", "UGX"),
    "Ukraina": ("Ukrainian Hryvnia", "UAH"),
    "Birlashgan Arab Amirliklari": ("UAE Dirham", "AED"),
    "Buyuk Britaniya": ("British Pound", "GBP"),
    "Amerika Qoʻshma Shtatlari": ("US Dollar", "USD"),
    "Urugvay": ("Uruguayan Peso", "UYU"),
    "Oʻzbekiston": ("Uzbekistani Som", "UZS"),
    "Vanuatu": ("Vanuatu Vatu", "VUV"),
    "Vatikan": ("Euro", "EUR"),
    "Venesuela": ("Venezuelan Bolívar", "VES"),
    "Vyetnam": ("Vietnamese Dong", "VND"),
    "Yaman": ("Yemeni Rial", "YER"),
    "Zambiya": ("Zambian Kwacha", "ZMW"),
    "Zimbabve": ("Zimbabwean Dollar", "ZWL"),
}
