"""
Geographic facts for quiz questions.
country_uz values must match keys in data.COUNTRIES.
"""

# (mountain_name_displayed, country_uz_key)
MOUNTAIN_FACTS = [
    ("Everest",        "Nepal"),
    ("K2",             "Pokiston"),
    ("Kanchenjunga",   "Hindiston"),
    ("Lhotse",         "Nepal"),
    ("Cho Oyu",        "Xitoy"),
    ("Makalu",         "Nepal"),
    ("Dhaulagiri",     "Nepal"),
    ("Manaslu",        "Nepal"),
    ("Annapurna",      "Nepal"),
    ("Nanga Parbat",   "Pokiston"),
    ("Gasherbrum I",   "Pokiston"),
    ("Gasherbrum II",  "Pokiston"),
    ("Elbrus",         "Rossiya"),
    ("Mont Blanc",     "Fransiya"),
    ("Matterhorn",     "Shveytsariya"),
    ("Mount Etna",     "Italiya"),
    ("Vesuvius",       "Italiya"),
    ("Olympus",        "Gretsiya"),
    ("Ararat",         "Turtsiya"),
    ("Kilimanjaro",    "Tanzaniya"),
    ("Mount Kenya",    "Keniya"),
    ("Aconcagua",      "Argentiniya"),
    ("Denali",         "AQSH"),
    ("Mount Logan",    "Kanada"),
    ("Popocatépetl",   "Meksika"),
    ("Mount Fuji",     "Yaponiya"),
    ("Mount Cook",     "Yangi Zelandiya"),
    ("Puncak Jaya",    "Indoneziya"),
    ("Table Mountain", "Janubiy Afrika"),
    ("Ben Nevis",      "Buyuk Britaniya"),
]

# (river_name_displayed, country_uz_key — main/best-known country)
RIVER_FACTS = [
    ("Nil",            "Misr"),
    ("Amazon",         "Braziliya"),
    ("Yangtze",        "Xitoy"),
    ("Mississippi",    "AQSH"),
    ("Yenisei",        "Rossiya"),
    ("Sariq daryo",    "Xitoy"),
    ("Ob",             "Rossiya"),
    ("Amur",           "Rossiya"),
    ("Lena",           "Rossiya"),
    ("Mekong",         "Vyetnam"),
    ("Volga",          "Rossiya"),
    ("Kongo",          "Kongo"),
    ("Niger",          "Nigeriya"),
    ("Dunay",          "Germaniya"),
    ("Gang",           "Hindiston"),
    ("Ind",            "Pokiston"),
    ("Reyn",           "Germaniya"),
    ("Sena",           "Fransiya"),
    ("Temza",          "Buyuk Britaniya"),
    ("Zambezi",        "Zambiya"),
    ("Apelsin",        "Janubiy Afrika"),
    ("Murray",         "Avstraliya"),
    ("Amudaryo",       "O'zbekiston"),
    ("Sirdaryo",       "O'zbekiston"),
    ("Dajla",          "Iroq"),
    ("Frot",           "Iroq"),
    ("Tigr",           "Iroq"),
    ("Missisipi",      "AQSH"),
    ("Kolumbiya",      "AQSH"),
    ("Orinoko",        "Venesuela"),
    ("Parana",         "Argentiniya"),
]

# (lake_name_displayed, country_uz_key — lake is in or borders)
LAKE_FACTS = [
    ("Kaspiy dengizi",  "Rossiya"),
    ("Baykal",          "Rossiya"),
    ("Viktoriya",       "Uganda"),
    ("Superyor",        "AQSH"),
    ("Gurron",          "Kanada"),
    ("Michigan",        "AQSH"),
    ("Tanganika",       "Tanzaniya"),
    ("Eri",             "AQSH"),
    ("Ontario",         "Kanada"),
    ("Volga",           "Rossiya"),
    ("Chad",            "Chad"),
    ("Orol dengizi",    "O'zbekiston"),
    ("Balxash",         "Qozog'iston"),
    ("Titicaca",        "Peru"),
    ("Nicara gua",      "Nikaragua"),
    ("Marakaibo",       "Venesuela"),
    ("Okeechobee",      "AQSH"),
    ("Van",             "Turtsiya"),
    ("Malavi",          "Malavi"),
    ("Issiqko'l",       "Qirg'iziston"),
]

# Variant-only: (question_text_en/uz/ru, choices, correct_idx)
# These are "who/what is the X" type facts
GEO_RECORDS = [
    {
        'uz': "🌍 Dunyodagi eng baland tog' qaysi?",
        'ru': "🌍 Какая самая высокая гора в мире?",
        'en': "🌍 What is the world's highest mountain?",
        'choices': {"uz": ["Everest", "K2", "Kilimanjaro", "Aconcagua"],
                    'ru': ["Эверест", "К2", "Килиманджаро", "Аконкагуа"],
                    'en': ["Everest", "K2", "Kilimanjaro", "Aconcagua"]},
        'correct': 0,
    },
    {
        'uz': "🌊 Dunyodagi eng uzun daryo qaysi?",
        'ru': "🌊 Какая самая длинная река в мире?",
        'en': "🌊 What is the world's longest river?",
        'choices': {"uz": ["Nil", "Amazon", "Yangtze", "Mississippi"],
                    'ru': ["Нил", "Амазонка", "Янцзы", "Миссисипи"],
                    'en': ["Nile", "Amazon", "Yangtze", "Mississippi"]},
        'correct': 0,
    },
    {
        'uz': "🌊 Dunyodagi eng chuqur ko'l qaysi?",
        'ru': "🌊 Какое самое глубокое озеро в мире?",
        'en': "🌊 What is the world's deepest lake?",
        'choices': {"uz": ["Baykal", "Kaspiy", "Viktoriya", "Tanganyika"],
                    'ru': ["Байкал", "Каспий", "Виктория", "Танганьика"],
                    'en': ["Baikal", "Caspian", "Victoria", "Tanganyika"]},
        'correct': 0,
    },
    {
        'uz': "🌍 Dunyodagi eng katta okean qaysi?",
        'ru': "🌍 Какой самый большой океан в мире?",
        'en': "🌍 What is the world's largest ocean?",
        'choices': {"uz": ["Tinch okean", "Atlantika", "Hind okean", "Arktika"],
                    'ru': ["Тихий", "Атлантический", "Индийский", "Северный Ледовитый"],
                    'en': ["Pacific", "Atlantic", "Indian", "Arctic"]},
        'correct': 0,
    },
    {
        'uz': "🌍 Dunyodagi eng katta cho'l qaysi?",
        'ru': "🌍 Какая самая большая пустыня в мире?",
        'en': "🌍 What is the world's largest desert?",
        'choices': {"uz": ["Antarktika", "Saxara", "Arabiston", "Gobi"],
                    'ru': ["Антарктика", "Сахара", "Аравийская", "Гоби"],
                    'en': ["Antarctica", "Sahara", "Arabian", "Gobi"]},
        'correct': 0,
    },
    {
        'uz': "🌍 Dunyodagi eng katta davlat (maydoni bo'yicha) qaysi?",
        'ru': "🌍 Самая большая страна в мире по площади?",
        'en': "🌍 The largest country by area?",
        'choices': {"uz": ["Rossiya", "Kanada", "AQSH", "Xitoy"],
                    'ru': ["Россия", "Канада", "США", "Китай"],
                    'en': ["Russia", "Canada", "USA", "China"]},
        'correct': 0,
    },
    {
        'uz': "👥 Dunyodagi eng ko'p aholiga ega davlat qaysi?",
        'ru': "👥 Самая населённая страна в мире?",
        'en': "👥 The world's most populous country?",
        'choices': {"uz": ["Hindiston", "Xitoy", "AQSH", "Indoneziya"],
                    'ru': ["Индия", "Китай", "США", "Индонезия"],
                    'en': ["India", "China", "USA", "Indonesia"]},
        'correct': 0,
    },
    {
        'uz': "🌊 Eng ko'p sho'r suv to'plangan joy qaysi?",
        'ru': "🌊 Самое солёное море в мире?",
        'en': "🌊 The world's saltiest body of water?",
        'choices': {"uz": ["O'lik dengiz", "Qizil dengiz", "Kaspiy", "Orol"],
                    'ru': ["Мёртвое море", "Красное море", "Каспий", "Аральское"],
                    'en': ["Dead Sea", "Red Sea", "Caspian Sea", "Aral Sea"]},
        'correct': 0,
    },
    {
        'uz': "⛰ Yevropadagi eng baland tog' qaysi?",
        'ru': "⛰ Самая высокая гора Европы?",
        'en': "⛰ The highest mountain in Europe?",
        'choices': {"uz": ["Elbrus", "Mont Blanc", "Matterhorn", "Olympus"],
                    'ru': ["Эльбрус", "Монблан", "Маттерхорн", "Олимп"],
                    'en': ["Elbrus", "Mont Blanc", "Matterhorn", "Olympus"]},
        'correct': 0,
    },
    {
        'uz': "🌊 Afrikadagi eng uzun daryo qaysi?",
        'ru': "🌊 Самая длинная река Африки?",
        'en': "🌊 The longest river in Africa?",
        'choices': {"uz": ["Nil", "Kongo", "Niger", "Zambezi"],
                    'ru': ["Нил", "Конго", "Нигер", "Замбези"],
                    'en': ["Nile", "Congo", "Niger", "Zambezi"]},
        'correct': 0,
    },
]
